name: dart_boost
description: A package for simple and fast dart development.
version: 0.0.1
author: aasirmutwalli22@gmail.com
homepage: https://github.com/aasirmutwalli22/dart_boost

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
